[package]
name = "hanulmodu"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hanulmodu"
crate-type = ["dylib"]

[dependencies]
